---
channels:
  ! '#twillers':
    operators:
    - wedgex
    - poemdexter
    - vaxinate
    - syntaxrigger
  ! '#spacestro':
    operators:
    - wedgex
    - poemdexter
    - vaxinate
    - poem_work
